### PR TITLE
feat: Skipping this action when repository is not inlcuded in ZenHub workspace

### LINKED ISSUE #19: The check should pass for people outside of Apify organization
Some of our repositories are getting PRs from outside collaborators, and this action will fail for those.

Example here:

https://github.com/apify/apify-docs/actions/runs/5706849566/job/15465929609

### PR DESCRIPTION
**Pull request by mtrunkat**
I want to:
- enable this for the tooling team, too, which means adding this to many repositories owned by them
- to make this easier, I want to enable this as an org-wide workflow - https://github.blog/changelog/2023-01-10-github-actions-support-for-organization-wide-required-workflows-public-beta/

But to be able to proceed with this, I updated this action to skip itself when the repository is not included in the ZenHub.

In addition to this, I did a tiny cleanup around the `main.js`.

Fixes #19

### CODE REVIEW

**Review by jirimoravcik — APPROVED** [review]
the new test is commented out on purpose?

**Comment by B4nan** [comment]
Does this also handle #19?

**Comment by mtrunkat** [comment]
@B4nan I added these few lines of code to fix it:

https://github.com/apify/pull-request-toolkit-action/pull/20/files#diff-4fab5baaca5c14d2de62d8d2fceef376ddddcc8e9509d86cfa5643f51b89ce3dR26
```js
        // This disables skips this action when run on a PR from external fork, i.e., when the fork is not a part of the organization.
        if (github.context.payload.pull_request?.base.repo.full_name.startsWith(`${ORGANIZATION}/`)) {
            core.warning(`Skipping toolkit action for PR from external fork: ${github.context.payload.pull_request?.base.repo.full_name}`);
            return;
        }
```

**Comment by mtrunkat** [comment]
@jirimoravcik It's not a real test. I use it only to test the action locally:

CleanShot 2023-08-04 at 09 24 14@2x

**Comment by mtrunkat** [comment]
One more addition - I improved the logging and fixed missing await. Tested on external repo here:

CleanShot 2023-08-04 at 09 43 55

**Comment by mtrunkat** [comment]
And the test on the external fork was done here: https://github.com/apify/pull-request-toolkit-action/pull/23

CleanShot 2023-08-04 at 09 59 02

**Comment by jirimoravcik** [comment]
> @jirimoravcik It's not a real test. I use it only to test the action locally:
> 
> CleanShot 2023-08-04 at 09 24 14@2x

Sry Mara, didn't notice. It's ok then

**Pull request merged**
